# Used by TestProxy.test_exception_in_init.

raise ValueError("Exception in __init__.py")
